### PR TITLE
Get source from pypi

### PR DESCRIPTION
**Pull request by xylar**
The source from GitHub has an incorrect (development) version of
the package, which propagates to the metadata and causes
`pip check` to fail on downstream packages.

This merge also adds `pip check` to tests.

It removes `six`, which is no longer a dependency.

It adds @xylar as a maintainer.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@rvalieris, I hope you don't mind me making these changes.  Also, I certainly do not insist on becoming a maintainer if you'd prefer to maintain this package on your own.

Conda-forge is wanting to use `pip check` on all python packages: https://github.com/conda-forge/conda-forge.github.io/issues/962

Currently, this is failing for packages that depend on `connexion` because of the versioning in the GitHub source code, e.g.:
```
apache-airflow 2.0.1 has requirement connexion[flask,swagger-ui]<3,>=2.6.0, but you have connexion 2020.0.dev1.
```

I verified that the source from pypi has the right version number in the metadata, so I think that would be the easiest fix.

**Comment by rvalieris** [comment]
Thank you for your work @xylar, your PR and offer to be a maintainer are very welcome.

**Comment by xylar** [comment]
Thanks very much, @rvalieris

**Pull request merged**
